### DISCUSSION TITLE
1BRC in Rust

### DISCUSSION THREAD

**Discussion by tumdum** [gunnarmorling/1brc#57] [Show and tell]
Nothing too exciting - mmap whole file, split it into slices (one per core), collect partial results and merge.

Code is here: https://github.com/tumdum/1brc/blob/main/src/main.rs 

Runs in ~15.5s on a m2pro

**Comment by PurpleMyst** [comment]
I had the same idea! Runs in `127.3ms` on a 13600k, however I am utilizing both rayon and fxhash.

https://github.com/PurpleMyst/1brc.rs/blob/main/src/main.rs

**Reply by tumdum** [reply]
Interesting, for me it takes `~50s` to run just `read_to_string`.

**Reply by PurpleMyst** [reply]
Looking better at my `measurements.txt` it seems to be cut-off. That's strange.

**Reply by PurpleMyst** [reply]
I'm probably just going to implement a `criterion` benchmark that measures throughput, as it seems I've not got the space for 1B rows.

**Reply by koyeung** [reply]
not sure if it is feasible to run on CI, with [iai](https://crates.io/crates/iai)?

```yaml
name: benchmark

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

  RUSTFLAGS: -Dwarnings

  # setup sccache for Rust; see https://github.com/Mozilla-Actions/sccache-action
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:

  iai:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: mozilla-actions/sccache-action@v0.0.3
    - uses: dtolnay/rust-toolchain@stable

    - run: sudo apt-get -y install valgrind

    - run: cargo bench --bench benchmark_by_cachegrind
```
